version: "3.4"
x-environment: &QUICKSTART_ENVIRONMENT
  # These are read from .env file. The values in the .env file maybe overriden by shell envvars
  NODE_ENV: 'production'
  PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
  PLAID_SECRET: ${PLAID_SECRET}
  PLAID_PRODUCTS: ${PLAID_PRODUCTS}
  PLAID_COUNTRY_CODES: ${PLAID_COUNTRY_CODES}
  PLAID_REDIRECT_URI: ${PLAID_REDIRECT_URI}
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: ["8000:8000"]
    environment:
      << : *QUICKSTART_ENVIRONMENT
